I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 150, in script
    $ inspected_items = perform_inspection(current_visitor.inventory)
  File "game/script.rpy", line 150, in <module>
    $ inspected_items = perform_inspection(current_visitor.inventory)
  File "game/script.rpy", line 66, in perform_inspection
    res.append(current_line)
NameError: name 'current_line' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 150, in script
    $ inspected_items = perform_inspection(current_visitor.inventory)
  File "C:\Users\jishe\Desktop\New folder (3)\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jishe\Desktop\New folder (3)\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 150, in <module>
    $ inspected_items = perform_inspection(current_visitor.inventory)
  File "game/script.rpy", line 66, in perform_inspection
    res.append(current_line)
NameError: name 'current_line' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Drilonis 1.0
Tue Jul  8 00:13:29 2025
